---
title: "Requesting rec letters from me"
---

If you were a student in one of my classes, and you would like to request a recommendation letter from me for a fellowship, postgrad application, or job application:

The [USD College of Arts & Sciences recommendation request guide](https://www.sandiego.edu/cas/student-resources/career-readiness/letters-recommendation.php) is a great place to start!

## If you might want a letter in the future

If you think you might want to ask me for a recommendation letter, **stop by my office hours to chat!** I enjoy hearing about the kinds of programs students are applying to, and talking to you will help me get a better sense for you as a person so that I can write you a strong, personalized letter.

_Come talk to me sooner rather than later,_ even if you aren't applying for a while! The sooner you declare your interest in soliciting a rec letter from me, the sooner I'll be able to make notes about your work in my class while my memory is fresher.

## If you are requesting a letter now

For all recommendation requests, please provide me with the following via email after you have come and talked to me about your application plans:

- An updated resume or CV
- A 1-paragraph statement explaining how your experience in my class relates to the program you're applying for
- A description of 2-3 specific ideas you would like me to highlight in my letter
- A list or Google spreadsheet, listing out for each of your applications:
  - The program website or job posting of each program you are applying to
  - The due date for each application
  - Any other need-to-know details to help me write a specific letter for that program
  
_I must receive your initial request at least **one month** before your earliest deadline in order to guarantee consideration._
